### ISSUE TITLE
it returns wrong altitude

### ISSUE THREAD

**Issue by berndhahnebach** [cmla/srtm4#10]
srtm4.srtm4(46.503,8.035)

gives for me:

>>> srtm4.srtm4(46.503,8.035)
608.334

https://www.openstreetmap.org/?mlat=46.503&mlon=8.035#map=15/46.5030/8.0350&layers=C
is ca 2725 m above sea leavel ...

**Comment by carlodef** [comment]
You're giving longitude and latitude in the wrong order: `srtm4.srtm4` receives the longitude as first argument, and the latitude as second argument: https://github.com/cmla/srtm4/blob/master/srtm4.py#L204

```
srtm4.srtm4(8.035, 46.503)
2773.88
```

**Comment by berndhahnebach** [comment]
OMG, thanks for the information.

**Comment by berndhahnebach** [comment]
> You're giving longitude and latitude in the wrong order: `srtm4.srtm4` receives the longitude as first argument, and the latitude as second argument: https://github.com/cmla/srtm4/blob/master/srtm4.py#L204
> 
> ```
> srtm4.srtm4(8.035, 46.503)
> 2773.88
> ```

but 2773 is not 2725 there is 50 meters difference ?

**Comment by glostis** [comment]
@berndhahnebach, as stated in the [docstring](https://github.com/cmla/srtm4/blob/b9656dbacf6253235b168554c86a959a74e326f3/srtm4.py#L208) of the `srtm4.srtm4` function, it returns:

> height(s) in meters above the WGS84 ellipsoid (not the EGM96 geoid)

If you want the height above sea level, you're most probably looking for the height with respect to the geoid.
This [geographiclib online utility](https://geographiclib.sourceforge.io/cgi-bin/GeoidEval?input=46.503+8.035&option=Submit) shows you that at your point of interest, the offset between the ellipsoid and the geoid is 50 meters, which explains the discrepancy you observe.

**Comment by berndhahnebach** [comment]
got it. Thanks for the information. 

Do you know a python module to convert the WGS84 (srtm4) into EGM96 (what is written in standard maps)?

**Comment by glostis** [comment]
Sure!

You can use the [pyproj](https://pyproj4.github.io/pyproj/stable/) package that relies on PROJ to do the transformation.

This snippet should do more or less what you want:
```python
import pyproj

# WGS84 with ellipsoid height as vertical axis
ellipsoid = pyproj.CRS.from_epsg(4979)
# WGS84 with Gravity-related height (EGM96)
geoid = pyproj.CRS("EPSG:4326+5773")

trf = pyproj.Transformer.from_crs(ellipsoid, geoid)
geoid_alts = trf.transform(lats, lons, ellipsoid_alts)  # beware of the order of arguments: lats, lons
```

**Comment by berndhahnebach** [comment]
great!
