### ISSUE TITLE
pip install doesn't work on Ubuntu 18

### ISSUE THREAD

**Issue by daviddemeij** [cmla/srtm4#6]
Installing this package doesn't seem to work on Ubuntu 18, I think it has something to do with the libtiff package (I tried installing different versions of this package but it still did not work unfortunately).

Any idea if there is an easy fix for this?
```
 -ltiff -o bin/srtm4
    src/srtm4.c:9:10: fatal error: tiffio.h: No such file or directory
     #include <tiffio.h>
              ^~~~~~~~~~
    compilation terminated.
    Makefile:15: recipe for target 'bin/srtm4' failed
```

**Comment by carlodef** [comment]
Hi @daviddemeij, on Ubuntu you need to install `libtiff-dev`, as written in the `README.md` :-)

**Comment by daviddemeij** [comment]
Hi @carlodef, thank you for the very quick response. I did install this package, but unfortunately for some reason it still doesn't work for me.

```
sudo apt-get install libtiff-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtiff-dev is already the newest version (4.0.9-5ubuntu0.3).
The following packages were automatically installed and are no longer required:
  libgeos-3.6.2 libproj12 linux-aws-headers-4.15.0-1040
  linux-aws-headers-4.15.0-1041 linux-aws-headers-4.15.0-1043
  linux-aws-headers-4.15.0-1044 linux-aws-headers-4.15.0-1048
  linux-aws-headers-4.15.0-1050 linux-aws-headers-4.15.0-1051
  python-pkg-resources
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 176 not upgraded.
```

**Comment by daviddemeij** [comment]
For now I am just using Ubuntu 16, so it is not an immediate problem for me, but I thought it would be nice if it works for Ubuntu 18 as well, since it is a very useful package.

**Comment by daviddemeij** [comment]
I tried it locally and now it works, I am not sure what I did different, maybe it was using `libtiff5-dev` instead of `libtiff-dev`. For reference I just did:
```
sudo apt-get update
sudo apt-get install libtiff5-dev
cd srtm4
make
pip install .
```
